version: '2'

services:
  lemonldap-app:
    image: tiredofit/lemonldap:2.0-alpine-latest
    container_name: lemonldap-app
    volumes:
    - ./data/etc/lemonldap-ng:/etc/lemonldap-ng
    - ./data/var/lib/lemonldap-ng/conf:/var/lib/lemonldap-ng/conf
    - ./data/var/lib/lemonldap-ng/sessions:/var/lib/lemonldap-ng/sessions
    - ./data/var/lib/lemonldap-ng/psessions:/var/lib/lemonldap-ng/psessions
    - ./logs:/www/logs
    #- ./assets/custom:/assets/custom
    environment:
    - VIRTUAL_HOST=sso.example.com,manager.sso.example.com,handler.sso.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=sso.example.com,manager.sso.example.com,handler.sso.example.com
    - LETSENCRYPT_EMAIL=dave@example.com

    - CONTAINER_NAME=lemonldap-app

    - API_HOSTNAME=api.manager.sso.example.com
    - MANAGER_HOSTNAME=manager.sso.example.com
    - PORTAL_HOSTNAME=sso.example.com
    - HANDLER_HOSTNAME=handler.sso.example.com
    networks:
      - proxy-tier
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
