version: '2'

services:
  lemonldap-handler-app:
    image: tiredofit/lemonldap:2.0-latest
    container_name: lemonldap-handler-app
    volumes:
    - ./data/etc/lemonldap-ng:/etc/lemonldap-ng
    - ./logs:/www/logs
    environment:
    - VIRTUAL_HOST=handler.sso.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=handler.sso.example.com
    - LETSENCRYPT_EMAIL=email@example.com

    - ZABBIX_HOSTNAME=lemonldap-handler-app

    - MODE=HANDLER
    
    - DOMAIN_NAME=example.com
    - HANDLER_HOSTNAME=handler.sso.example.com
    - HANDLER_ALLOWED_IPS=172.16.1.0/24,192.168.0.1,10.0.0.0/12
     
    - CONFIG_TYPE=SOAP
    - SOAP_HOST=https://sso.example.com/index.pl/config 
    - SOAP_USER=dwho
    - SOAP_PASS=dwho

    networks:
      - proxy-tier
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always


networks:
  proxy-tier:
    external:
      name: nginx-proxy
